name: "Setup CDK"
description: "Sets up the AWS CDK environment"

inputs:
  example_input:
    description: "An example input"
    required: false
    default: "default_value"

runs:
  using: "composite"
  steps:
    - name: Install CDK
      shell: bash
      run: |
        npm install -g aws-cdk
