name: "Setup CDK"
description: "Sets up the AWS CDK environment"

runs:
  using: "composite"
  steps:
     - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

    - name: Install CDK
      shell: bash
      run: |
        npm install -g aws-cdk
