name: Setup CDK

description: "Sets up Node.js and CDK environment"

inputs:
  node-version:
    description: "Node.js version"
    default: "18"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install CDK and Dependencies
      run: |
        cd CDK
        npm install
