name: Configuration

on:
  workflow_dispatch:

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      AWS_ACCOUNT_ID: ${{ steps.set-vars.outputs.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ steps.set-vars.outputs.AWS_REGION }}
    steps:
      - name: Set environment variables
        id: set-vars
        run: |
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
