name: Setup and Deploy Stack

on:
  push:
    branches:
      - master
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install CDK and Dependencies
        run: |
          cd CDK
          npm install

      - name: Bootstrap CDK Environment
        run: |
          cd CDK
          npx cdk bootstrap aws://637423502407/us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"

      - name: Deploy CDK Stack
        run: |
          cd CDK
          npx cdk deploy --all --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"

      - name: Notify Deployment Status
        if: ${{ success() }}
        uses: actions/github-script@v6
        with:
          script: |
            console.log("Deployment succeeded, triggering docker-build-push.yml");
