name: Setup and Deploy ECR

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

jobs:
  deply-ecr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup CDK
        uses: ./.github/actions/action

      - name: Deploy CDK Stack
        run: |
          cd CDK
          npx cdk deploy --all --require-approval never
