name: Setup and Deploy Stack

on:
  push:
    branches:
      - master
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      ecr-uri: ${{ steps.output-ecr-uri.outputs.ecr-uri }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install CDK and Dependencies
        run: |
          cd CDK
          npm install

      - name: Bootstrap CDK Environment
        run: |
          cd CDK
          npx cdk bootstrap aws://637423502407/us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"

      - name: Deploy CDK Stack
        id: deploy
        run: |
          cd CDK
          npx cdk deploy --all --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"

      - name: Output ECR URI
        id: output-ecr-uri
        run: |
          set -x  # Enable command tracing
          # Print current AWS CLI configuration
          aws configure list
          # Print AWS CLI version
          aws --version
          # Describe stacks and handle potential errors
          ECR_URI=$(aws cloudformation describe-stacks --stack-name IoTStack --query "Stacks[0].Outputs[?OutputKey=='EcrRepositoryUri'].OutputValue" --output text || echo "Failed to get ECR URI")
          echo "ECR_URI=$ECR_URI"
          echo "::set-output name=ecr-uri::$ECR_URI"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
