name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Print current working directory
        run: pwd

      - name: List files in current directory
        run: ls -R

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup CDK
        uses: ./.github/actions

      - name: Clean CDK Context
        run: |
          cd CDK
          rm -rf node_modules/.cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsAdminRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Bootstrap CDK Environment
        run: |
          cd CDK
          npx cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ secrets.AWS_REGION }}
