name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Setup and Deploy Stack"] # Must match the name of the deploy workflow
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Assume GitHubActionsAdminRole
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::654654232198:role/GitHubActionsAdminRole
          aws-region: us-east-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build and Push Docker image
        run: |
          echo "Building Docker image from IoT_GPS"
          docker build -t ${{ secrets.ECR_REGISTRY }}/my-iot-gps-app:latest -f IoTMockSensors/IoT_GPS/Dockerfile IoTMockSensors/IoT_GPS
          docker push ${{ secrets.ECR_REGISTRY }}/my-iot-gps-app:latest
