name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Setup and Deploy Stack"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Assume GitHubActionsAdminRole
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsAdminRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Print ECR URI
        run: echo "ECR_URI=${{ needs.deploy.outputs.ecr-uri }}"

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ needs.deploy.outputs.ecr-uri }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build and Push Docker image
        run: |
          echo "Building Docker image from IoT_GPS"
          docker build -t ${{ needs.deploy.outputs.ecr-uri }}/my-iot-gps-app:latest -f IoTMockSensors/IoT_GPS/Dockerfile IoTMockSensors/IoT_GPS
          docker push ${{ needs.deploy.outputs.ecr-uri }}/my-iot-gps-app:latest
