name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Setup and Deploy Stack"] # The name of the deploy workflow
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image
        run: |
          echo "Building Docker image from IoT_GPS"
          docker build -t ${{ env.ECR_URI }}/my-iot-gps-app:latest -f IoTMockSensors/IoT_GPS/Dockerfile IoTMockSensors/IoT_GPS
          docker push ${{ env.ECR_URI }}/my-iot-gps-app:latest
        env:
          ECR_URI: ${{ secrets.ECR_URI }}
